# Generated by Django 4.1.2 on 2024-01-09 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paint_app', '0002_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Package Name')),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('Warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('shop_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_1', to=settings.AUTH_USER_MODEL, verbose_name='shop_1')),
            ],
        ),
    ]
