# Generated by Django 4.1.2 on 2024-01-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint_app', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='cust_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Customer phone'),
        ),
        migrations.AlterField(
            model_name='book',
            name='shop_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Shop phone'),
        ),
    ]
