# Generated by Django 4.1.2 on 2024-01-11 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paint_app', '0005_book_status_alter_book_cust_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site Name')),
                ('worker', models.IntegerField(blank=True, null=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('images', models.ImageField(blank=True, null=True, upload_to='Site images/', verbose_name='Site Images')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
        ),
    ]
