# Generated by Django 4.1.2 on 2024-01-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paint_app', '0008_alter_message_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='client',
        ),
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
